-- CONSOLIDATED_SCHEMA_FOR_DASHBOARD.sql
-- Single-file consolidated schema + migrations for Supabase SQL editor
-- Generated by inlining:
--   supabase/01_DATABASE_SCHEMA.sql
--   supabase/migrations/* (ordered, initial_schema migration skipped because it's duplicate)
-- Review carefully before running. BACKUP your DB before applying.

-- =====================================================================
-- 01_DATABASE_SCHEMA.sql (inlined)
-- =====================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- SanibonaniSave — CONSOLIDATED DATABASE SCHEMA
-- Version: 4.0 (Consolidated May 2026)
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. DROP PUBLIC SCHEMA FIRST to remove all foreign key constraints and start fresh
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

-- 2. RESTORE PERMISSIONS for the new public schema
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;
GRANT ALL ON SCHEMA public TO anon;
GRANT ALL ON SCHEMA public TO authenticated;
GRANT ALL ON SCHEMA public TO service_role;

-- 3. Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 4. UTILITY FUNCTIONS
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = NOW();
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 5. PROFILES (Global user data synced with Auth)
CREATE TABLE public.profiles (
	id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
	full_name   TEXT CHECK (char_length(full_name) >= 3),
	email       TEXT CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
	role        TEXT DEFAULT 'member' CHECK (role IN ('platform_admin', 'group_admin', 'member')),
	created_at  TIMESTAMPTZ DEFAULT NOW(),
	updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Function to handle new user creation and sync to profiles
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
	INSERT INTO public.profiles (id, full_name, email, role)
	VALUES (
		NEW.id,
		COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', ''),
		NEW.email,
		COALESCE(NEW.raw_user_meta_data->>'role', 'member')
	);
	RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to sync auth.users to public.profiles
CREATE TRIGGER on_auth_user_created
	AFTER INSERT ON auth.users
	FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 6. GROUPS
CREATE TABLE public.groups (
	id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	name                   TEXT NOT NULL CHECK (char_length(name) >= 3),
	type                   TEXT NOT NULL DEFAULT 'other' CHECK (type IN ('burial_society', 'stokvel', 'rosca', 'investment_club', 'emergency_fund', 'community_savings', 'tontine', 'other')),
	province               TEXT,
	city                   TEXT,
	township               TEXT,
	description            TEXT,
	logo_emoji             TEXT DEFAULT '🤝',
	joining_fee            NUMERIC(10,2) DEFAULT 0 CHECK (joining_fee >= 0),
	monthly_contribution   NUMERIC(10,2) DEFAULT 0 CHECK (monthly_contribution >= 0),
	late_fee               NUMERIC(10,2) DEFAULT 0 CHECK (late_fee >= 0),
	late_fee_grace_days    INTEGER DEFAULT 5 CHECK (late_fee_grace_days >= 0),
	probation_months       INTEGER DEFAULT 3 CHECK (probation_months >= 0),
	payment_due_day        INTEGER DEFAULT 28 CHECK (payment_due_day >= 1 AND payment_due_day <= 28),
	max_members            INTEGER DEFAULT 50 CHECK (max_members > 0),
	current_members        INTEGER DEFAULT 0 CHECK (current_members >= 0),
	is_public              BOOLEAN DEFAULT TRUE,
	allow_partial_payment  BOOLEAN DEFAULT FALSE,
	auto_suspend_after     INTEGER DEFAULT 2 CHECK (auto_suspend_after > 0),
	bank_name              TEXT,
	account_number         TEXT CHECK (account_number IS NULL OR account_number ~ '^[0-9]{7,13}$'),
	branch_code            TEXT CHECK (branch_code IS NULL OR branch_code ~ '^[0-9]{6}$'),
	account_type           TEXT DEFAULT 'Savings',
	gateway_public_key     TEXT,
	balance                NUMERIC(12,2) DEFAULT 0,
	admin_user_id          UUID REFERENCES auth.users(id) NOT NULL,
	fee_status             TEXT DEFAULT 'due' CHECK (fee_status IN ('paid', 'due', 'warning', 'suspended', 'pending_activation')),
	registration_paid      BOOLEAN DEFAULT FALSE,
	is_platform_suspended  BOOLEAN DEFAULT FALSE,
	constitution_url       TEXT,
	constitution_status    TEXT DEFAULT 'pending' CHECK (constitution_status IN ('pending', 'verified', 'rejected')),
	latitude               FLOAT8,
	longitude              FLOAT8,
	geohash                TEXT,
	max_beneficiaries      INTEGER DEFAULT 0 CHECK (max_beneficiaries >= 0),
	beneficiary_increase_pct NUMERIC(5,2) DEFAULT 0 CHECK (beneficiary_increase_pct >= 0),
	goal_amount            NUMERIC(12,2) DEFAULT 0 CHECK (goal_amount >= 0),
	period_months          INTEGER DEFAULT 12 CHECK (period_months > 0),
	rosca_rotation_method  TEXT NOT NULL DEFAULT 'fixed' CHECK (rosca_rotation_method IN ('fixed', 'random_draw', 'need_based', 'auction')),
	loan_interest_rate     NUMERIC(5,2) DEFAULT 0 CHECK (loan_interest_rate >= 0),
	loan_max_amount        NUMERIC(12,2) DEFAULT 0 CHECK (loan_max_amount >= 0),
	loan_max_months        INTEGER DEFAULT 12 CHECK (loan_max_months > 0),
	created_at             TIMESTAMPTZ DEFAULT NOW(),
	updated_at             TIMESTAMPTZ DEFAULT NOW()
);


