-- 07_consolidate_and_cleanup.sql
-- Purpose: Apply consolidated schema + seed in a controlled order and produce a
-- list of redundant legacy SQL files that can be archived or removed.
--
-- USAGE (development/staging only):
-- 1) Review the REDUNDANT_FILES array below and confirm you want to archive/remove them.
-- 2) Run the consolidated apply sequence (this file references existing consolidated
--    SQL artifacts that already exist in the repo). It is safe to run multiple times.
-- 3) Archive or delete redundant files after a verified test on dev.
--
-- SAFETY: This script does not drop or delete files on disk. It only documents the
-- files considered redundant and provides the recommended execution order for the DB.

-- Recommended execution order (idempotent wrappers exist for most steps):
-- 1) Apply consolidated schema only (safe for fresh DB):
--    \i ../CONSOLIDATED_SCHEMA_FOR_DASHBOARD.sql
--
-- 2) Apply consolidated security & RLS / helper functions (if present):
--    \i ../02_SECURITY_AND_RLS.sql
--
-- 3) Apply engineering/performance helpers (functions, indexes, views):
--    \i ../39_ENGINEERING_PERFORMANCE_OPTIMIZATIONS.sql
--
-- 4) Apply consolidated safe seed for dashboard/dev:
--    \i ../CONSOLIDATED_FOR_DASHBOARD_SCHEMA_PLUS_SAFE_SEED.sql
--
-- 5) Optional: run any verification scripts (e.g., verify test data)
--    \i ../22_SEED_TEST_DATA_10_GROUPS_100_MEMBERS_SAFE.sql

-- Execute the consolidated sequence below when you are ready (uncomment to run):

-- \i ../CONSOLIDATED_SCHEMA_FOR_DASHBOARD.sql
-- \i ../02_SECURITY_AND_RLS.sql
-- \i ../39_ENGINEERING_PERFORMANCE_OPTIMIZATIONS.sql
-- \i ../CONSOLIDATED_FOR_DASHBOARD_SCHEMA_PLUS_SAFE_SEED.sql

-- =======================
-- REDUNDANT / ARCHIVE SUGGESTION
-- =======================
-- The files listed below are legacy or fragmented artifacts that were consolidated
-- into the consolidated files above. After you have tested the consolidated apply
-- on a development environment and verified data & RLS behavior, you can safely
-- move these into an archive folder (e.g., supabase/archived_sql/) or delete them.
-- DO NOT remove them until you have a verified backup and tested restores.

-- Suggested redundant files (review each before action):
-- 01_DATABASE_SCHEMA.sql
-- 03_PLATFORM_ADMIN_SETUP.sql
-- 04_MIGRATIONS_AND_UPDATES.sql
-- 04_PLATFORM_ADMIN_AUTH_ALIGNMENT.sql
-- 07_MISSING_TABLES_AND_COLUMNS.sql
-- 08_SMALL_STRESS_TEST_SEED.sql
-- 09_COMPREHENSIVE_TEST_SEED.sql
-- 10_SCALED_TEST_SEED_300.sql
-- 11_SEED_TEST_DATA_10_GROUPS_100_MEMBERS.sql
-- 12_VERIFY_TEST_DATA_10_GROUPS_100_MEMBERS.sql
-- 13_CREATE_TEST_LOGIN_PROFILES.sql
-- 14_VERIFY_TEST_LOGIN_PROFILES.sql
-- 15_CLEANUP_TEST_LOGIN_PROFILES.sql
-- 16_PLATFORM_MEMBER_BEHAVIOR_INSIGHTS.sql
-- 17_SEED_DEBUG_LOGIC_SCENARIOS.sql
-- 18_VERIFY_DEBUG_LOGIC_SCENARIOS.sql
-- 19_CLEANUP_DEBUG_LOGIC_SCENARIOS.sql
-- 20_RUN_DEBUG_LOGIC_SEED_AND_VERIFY.sql
-- 21_RUN_DEBUG_LOGIC_CLEANUP.sql
-- 22_SEED_TEST_DATA_10_GROUPS_100_MEMBERS_SAFE.sql
-- 23_VERIFY_TEST_DATA_10_GROUPS_100_MEMBERS_SAFE.sql
-- 24_PLATFORM_ADMIN_RLS_HOTFIX.sql
-- 25_SEED_FULL_APP_E2E.sql
-- 26_VERIFY_FULL_APP_E2E.sql
-- 27_ADD_ROSCA_ROTATION_METHOD.sql
-- 28_ARCHITECTURE_MODEL_SCHEMA_TEMPLATES.sql
-- 29_ALIGN_VALIDATION_CONSTRAINTS_WITH_APP.sql
-- 30_CONSOLIDATED_RLS_ALIGNMENT.sql
-- 31_ATOMIC_BALANCE_UPDATES.sql
-- 32_GROUP_VOTING_AND_MULTI_ADMIN.sql
-- 33_REBUILD_DATABASE_WITH_TEST_SEED.sql
-- 33_REMOVE_YOCO_FROM_DISBURSEMENTS.sql
-- 35_FULL_SYSTEM_REBUILD.sql
-- 36_DASHBOARD_FULL_REBUILD.sql
-- 37_DASHBOARD_SEED_DATA.sql
-- 38_DASHBOARD_COMPREHENSIVE_SEED.sql
-- 40_ADD_BENEFICIARY_FACE_PHOTO.sql

-- If you want this file to automatically move files into an archive folder, use the
-- companion PowerShell generator script (08_generate_inlined_consolidated.ps1) which
-- can also create an inlined consolidated SQL for easy application in one command.

-- End of file

